### ISSUE TITLE
Why not use fossil-scm ?

### ISSUE THREAD

**Issue by mingodad** [cannadayr/git-sqlite#1]
An interesting idea and why not using the self contained fossil-scm instead of git ?
Cheers !

**Comment by cannadayr** [comment]
I considered that, however when I looked into it I did not see a similar feature implemented in fossil.

The reasons I ended up using git:

1.) most of the projects I interact with use git
2.) most of the projects I write are in git

Remember this is not tracking the repo in a sqlite database (as in fossil), its instead tracking a binary database with a VCS, and using sqldiff to give a human readable output when diffing states. If fossil can do something similar that you're aware of I'd be interested, but its not exactly a high priority for me.

**Comment by cannadayr** [comment]
BTW it looks like you can do something similar with fossil. Most of the logic should be similar.

https://www.fossil-scm.org/xfer/help?cmd=diff-binary

**Comment by cannadayr** [comment]
Closing this issue. If you'd like to port this to fossil feel free to open a new issue or email me! (address on github profile). I think it'd be great for the fossil community to have something like this (if they don't already), since most of the implementation relies on their previous work.
